# .goreleaser.yaml
version: 2

project_name: scrapedoctl

before:
  hooks:
    - go mod tidy

builds:
  - id: default
    binary: scrapedoctl
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    main: ./cmd/scrapedoctl
    ldflags:
      - >-
        -s -w
        -X github.com/mr-pmillz/scrapedoctl/internal/version.Version={{.Version}}
        -X github.com/mr-pmillz/scrapedoctl/internal/version.GitCommit={{.ShortCommit}}
        -X github.com/mr-pmillz/scrapedoctl/internal/version.BuildDate={{.Date}}

upx:
  - enabled: true
    compress: best
    ids: [default]
    goos: [linux, windows]
    goarch: [amd64]

nfpms:
  - id: scrapedoctl
    package_name: scrapedoctl
    file_name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_
      {{- if eq .Arch "amd64" }}x86_64{{ else }}{{ .Arch }}{{ end }}
    vendor: mr-pmillz
    maintainer: Pavel Lavrukhin <46395539+dantte-lp@users.noreply.github.com>
    description: Scrape.do CLI & MCP Server
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    contents:
      - src: ./completions/scrapedoctl.bash
        dst: /usr/share/bash-completion/completions/scrapedoctl
      - src: ./completions/scrapedoctl.zsh
        dst: /usr/share/zsh/vendor-completions/_scrapedoctl
      - src: ./completions/scrapedoctl.fish
        dst: /usr/share/fish/vendor_completions.d/scrapedoctl.fish
      - src: ./completions/scrapedoctl.psm1
        dst: /usr/share/powershell/Modules/scrapedoctl/scrapedoctl.psm1
      - src: ./completions/scrapedoctl.psd1
        dst: /usr/share/powershell/Modules/scrapedoctl/scrapedoctl.psd1

archives:
  - formats:
      - tar.gz
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md
      - SECURITY.md
      - completions/*
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
