#
# Module manifest for module 'scrapedoctl'
#
# Generated by: Pavel Lavrukhin
#
# Generated on: 03/21/2026
#

@{

# Script module or binary module file associated with this manifest.
RootModule = './scrapedoctl.psm1'

# Version number of this module.
ModuleVersion = '0.1.0'

# ID used to uniquely identify this module
GUID = '46c76871-3d90-4cd5-a970-ad7869c5d086'

# Author of this module
Author = 'Pavel Lavrukhin'

# Company or vendor of this module
CompanyName = 'mr-pmillz'

# Copyright statement for this module
Copyright = '(c) Pavel Lavrukhin. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Advanced PowerShell support for Scrape.do CLI'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '7.4'

# Functions to export from this module
FunctionsToExport = @('Invoke-Scrapedoctl')

# Cmdlets to export from this module
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module
AliasesToExport = @('scrapedoctl')

PrivateData = @{
    PSData = @{
        # Tags = @()
        # LicenseUri = ''
        # ProjectUri = ''
    }
}

}
